--
-- INITIAL SQL SCRIPT
--

CREATE DATABASE EXPENSE;

CREATE TABLE USERS (
    ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
   	USERNAME VARCHAR(255) NOT NULL,
   	PASSWORD VARCHAR(500) NOT NULL,
   	EMAIL VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE TRANSACTIONS (
    ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    USER_ID BIGINT UNSIGNED NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    AMOUNT FLOAT NOT NULL,
    PRIMARY KEY(ID)
);

ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID);




CREATE TABLE INCOME_TYPES (
	ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE INCOME_TYPES ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

CREATE TABLE INCOMES (
	ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	INCOME_TYPE_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE EXPENSE.INCOMES ADD CONSTRAINT INCOMES_TRANSACTIONS_FK FOREIGN KEY (ID) REFERENCES EXPENSE.TRANSACTIONS(ID);
ALTER TABLE INCOMES ADD FOREIGN KEY (INCOME_TYPE_ID) REFERENCES INCOME_TYPES(ID);




CREATE TABLE FIXED_EXPENSE_TYPES (
	ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE FIXED_EXPENSE_TYPES ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

CREATE TABLE FIXED_EXPENSES (
	ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	FIXED_EXPENSES_TYPE_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE EXPENSE.FIXED_EXPENSES ADD CONSTRAINT FIXED_EXPENSES_TRANSACTIONS_FK FOREIGN KEY (ID) REFERENCES EXPENSE.TRANSACTIONS(ID);
ALTER TABLE FIXED_EXPENSES ADD FOREIGN KEY (FIXED_EXPENSES_TYPE_ID) REFERENCES FIXED_EXPENSE_TYPES(ID);




CREATE TABLE VARIABLE_EXPENSE_TYPES (
	ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE VARIABLE_EXPENSE_TYPES ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

CREATE TABLE VARIABLE_EXPENSES (
	ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	VARIABLE_EXPENSES_TYPE_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE EXPENSE.VARIABLE_EXPENSES ADD CONSTRAINT VARIABLE_EXPENSES_TRANSACTIONS_FK FOREIGN KEY (ID) REFERENCES EXPENSE.TRANSACTIONS(ID);
ALTER TABLE VARIABLE_EXPENSES ADD FOREIGN KEY (VARIABLE_EXPENSES_TYPE_ID) REFERENCES VARIABLE_EXPENSE_TYPES(ID);